Repository JEToP/jetop_credentials_backend, pull requests merged in 2020-10, with the labels that each got.

#6 Implement Credential model, repository, controller
  src/controllers/credential.controller.ts
  src/controllers/index.ts
  src/models/credential.model.ts
  src/models/index.ts
  src/repositories/credential.repository.ts
  src/repositories/index.ts
  tsconfig.json
Labels: enhancement

#8 Implement Service model, repository, controller #1
  src/controllers/index.ts
  src/controllers/service.controller.ts
  src/models/index.ts
  src/models/service.model.ts
  src/repositories/index.ts
  src/repositories/service.repository.ts
Labels: enhancement

#10 Implemented history's model, repository and controller
  src/controllers/history.controller.ts
  src/controllers/index.ts
  src/models/history.model.ts
  src/models/index.ts
  src/repositories/history.repository.ts
  src/repositories/index.ts
Labels: hacktoberfest-accepted

#11 Add Credential hasMany histories relation #9
  src/controllers/credential-history.controller.ts
  src/controllers/index.ts
  src/models/credential.model.ts
  src/models/history.model.ts
  src/repositories/credential.repository.ts
Labels: hacktoberfest-accepted

#12 Add Service hasMany Credential relation
  src/controllers/index.ts
  src/controllers/service-credential.controller.ts
  src/models/credential.model.ts
  src/models/service.model.ts
  src/repositories/service.repository.ts
Labels: hacktoberfest-accepted

#13 Add History belongsTo Credential relation #9
  src/controllers/history-credential.controller.ts
  src/controllers/index.ts
  src/models/history.model.ts
  src/repositories/history.repository.ts
Labels: enhancement, hacktoberfest-accepted

#14 Encryption implementation #5
  package-lock.json
  package.json
  src/encryption/encryption.ts
  src/repositories/history.repository.ts
Labels: enhancement, hacktoberfest-accepted

#15 Added a belongsTo relation between from Credential to Service
  src/controllers/credential-service.controller.ts
  src/controllers/index.ts
  src/models/credential.model.ts
  src/repositories/credential.repository.ts
  tsconfig.json
Labels: enhancement, hacktoberfest-accepted

#16 Added an auto update and auto migrate call after boot
  src/index.ts
Labels: enhancement, hacktoberfest-accepted
